apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-envvars
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ default "" .Values.api.username | b64enc | quote }}
  password: {{ default "" .Values.api.password | b64enc | quote }}

  PORT                      = var.port
  STAGE                     = var.stage
  DEBUG                     = ""