apiVersion: v1
kind: Secret
metadata:
   name: {{ .Values.image.secretName }}
   labels:
     app: {{ template "fullname" . }}
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
type: "kubernetes.io/dockerconfigjson"
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | b64enc | quote }}