apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      component: frontend
      app: {{ template "fullname" . }}
