{{- if eq .Values.ingress.class "gce" -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: api-sockets-backendconfig
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  timeoutSec: 604800
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: api-recording-backendconfig
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  timeoutSec: 604800
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: api-frontend-config
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  sslPolicy: ssl-policy-{{ .Values.stage }}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end -}}
