{{- if eq .Values.ingress.class "gce" -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cobrowse-api-ssl
spec:
  domains:
    - {{ .Values.domain }}
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: api-sockets-backendconfig
spec:
  timeoutSec: 604800
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: api-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end -}}