apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-proxy-envvars
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  PORT: {{ default "8080" .Values.proxy.port | b64enc | quote }}
  STAGE: {{ default "" .Values.stage | b64enc | quote }}
  DEBUG: {{ default "" .Values.proxy.debug | b64enc | quote }}
  mongo_url: {{ default "" .Values.mongoUrl | b64enc | quote }}
  redis_url: {{ default "" .Values.redisUrl | b64enc | quote }}
  frontend_url              = "https://${var.domain}"
  smtp_url: {{ default "" .Values.smtpUrl | b64enc | quote }}
  control__url_template     = "https://${var.domain}"
  streaming__url_template   = "https://${var.domain}"
  streaming__default_region = "api"
  streaming__locate_url     = "https://${var.domain}/sockets/1/region"
  license_key: {{ default "" .Values.licenseKey | b64enc | quote }}
  account_creators: {{ default "" .Values.accountCreators | b64enc | quote }}
  superusers: {{ default "" .Values.superusers | b64enc | quote }}