apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-recording-envvars
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  PORT: {{ default "8080" .Values.recording.port | b64enc | quote }}
  STAGE: {{ default "" .Values.stage | b64enc | quote }}
  DEBUG: {{ default "" .Values.recording.debug | b64enc | quote }}