apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recording-pdb
spec:
  minAvailable: {{ ternary "50%" 0 (ge  (int .Values.recording.replicas) 2) }}
  selector:
    matchLabels:
      component: recording
      app: {{ template "fullname" . }}
