apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recording-pdb
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      component: recording
      app: {{ template "fullname" . }}
