apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sockets-envvars
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  PORT: {{ default "8080" .Values.sockets.port | b64enc | quote }}
  STAGE: {{ default "" .Values.stage | b64enc | quote }}
  DEBUG: {{ default "" .Values.sockets.debug | b64enc | quote }}
  api_url: {{ default "" .Values.apiUrl | b64enc | quote }}
  peering_port: {{ default "" .Values.peeringPort | b64enc | quote }}
  peering_token: {{ default "" .Values.peeringToken | b64enc | quote }}
  redis_url: {{ default "" .Values.redisUrl | b64enc | quote }}