apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sockets-envvars
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
type: Opaque
data:
  {{- if .Values.sockets.peeringToken }}
  peering_token: {{ .Values.sockets.peeringToken | quote }}
  {{- else }}
  peering_token:: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  redis_url: {{ default "" .Values.redis.url | b64enc | quote }}
