apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-sockets
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    component: sockets
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
  {{- range $key, $value := .Values.sockets.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  serviceName: {{ .Release.Name }}-sockets-headless
  # default to 2 given the PodDisruptionBudget set to minAvailable: 1
  replicas: {{ .Values.sockets.replicas | default "2" }}
  selector:
    matchLabels:
      component: sockets
      stage: {{ .Values.stage | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/sockets-secret.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    {{- if .Values.sockets.pod }}
      {{- range $key, $value := .Values.sockets.pod.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
      labels:
        app: {{ template "fullname" . }}
        component: sockets
        stage: {{ .Values.stage | quote }}
    spec:
    {{- if .Values.sockets.nodeSelector}}
      nodeSelector:{{ toYaml .Values.sockets.nodeSelector | nindent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - sockets
              topologyKey: "kubernetes.io/hostname"
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-sockets-envvars
        - configMapRef:
            name: {{ .Release.Name }}-sockets-custom-envvars
            optional: true
        - secretRef:
            name: {{ .Release.Name }}-sockets-envvars
        - secretRef:
            name: {{ .Release.Name }}-sockets-custom-envvars
            optional: true
        image: {{ (.Values.sockets.image).ref | default (include "image" (dict "repo" .Values.image.repo "image" "cobrowse-api-sockets-enterprise:1.15.0" )) }}
        {{- if (.Values.sockets.image).pullPolicy }}
        imagePullPolicy: {{ (.Values.sockets.image).pullPolicy }}
        {{- end}}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: sockets
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: "/data"
          name: data-traces
        resources:
          limits:
            cpu: {{ coalesce .Values.sockets.limits.cpu .Values.sockets.cpu "250m" }}
            memory: {{ coalesce .Values.sockets.limits.memory .Values.sockets.memory "512Mi" }}
          requests:
            cpu: {{ .Values.sockets.cpu | default "250m" }}
            memory: {{ .Values.sockets.memory | default "512Mi" }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext:{{ include "defaultSecurityContext" . | nindent 10 }}
          runAsGroup: {{ (.Values.sockets.runAs).group | default "1000" }}
          runAsUser: {{ (.Values.sockets.runAs).user | default "1000" }}
        {{- end }}
      imagePullSecrets:
      - name: {{ .Release.Name }}-docker-cfg
      volumes:
      - name: data-traces
{{- if .Values.storage }}
        persistentVolumeClaim:
          claimName: {{ (.Values.sockets.storage).persistentVolumeClaimName | default (printf "%s-sockets-pvc" .Release.Name) | quote }}
{{- else }}
        emptyDir:
          sizeLimit: 1Mi
{{- end }}
      serviceAccountName: {{ .Values.serviceAccountName | default "" }}
      automountServiceAccountToken: false
