{{- if and (.Values.storage) (or (.Values.storage.class) (eq .Values.storage.class "")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-sockets-pvc
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.class }}
  storageClassName: {{ .Values.storage.class | quote }}
{{- end }}
{{- end }}
