name: Bump service image
on:
  workflow_dispatch:
    inputs:
      component:
        description: The helm service component to update
        type: choice
        options:
          - api
          - frontend
          - proxy
          - recording
          - sockets
          - virtual-agent
        required: true
      component_version:
        description: The new version of the component
        type: string
        required: true
jobs:
  bump-image-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.COBROWSE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COBROWSE_BOT_KEY }}
          permission-contents: write

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure Git
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          gh auth setup-git
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Resolve deployment file
        run: echo 'DEPLOYMENT_FILE_PATH="templates/${{ inputs.component }}-${{ inputs.component == 'sockets' && 'statefulset' || 'deployment' }}.yaml"' >> $GITHUB_ENV

      - name: Checkout source code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Update deployment version
        run: sed -Ei 's/(image:.*-enterprise):[0-9.]+/\1:${{ inputs.component_version }}/g' "${{ env.DEPLOYMENT_FILE_PATH }}"

      - name: Commit version bump
        run: |
          git add "${{ env.DEPLOYMENT_FILE_PATH }}"
          git commit -m "chore(${{ inputs.component }}): bump image version to ${{ inputs.component_version }}"
          git push
