name: Dispatch helm update
on:
  workflow_call:
    inputs:
      repo:
        description: The target repository to dispatch the version update
        required: true
        type: string
      version:
        description: The new helm version to apply
        required: true
        type: string
permissions: {}
jobs:
  dispatch-update-helm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: cobrowseio/actions/.github/actions/git-auth@master
        id: app-token
        with:
          client-id: ${{ vars.COBROWSE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COBROWSE_BOT_KEY }}
          permission-actions: write
          repositories: ${{ inputs.repo }}
      - name: Repository dispatch
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: '${{ inputs.repo }}',
              workflow_id: 'bump-helm-version.yaml',
              ref: 'master',
              inputs: {
                version: '${{ inputs.version }}'
              }
            })
