name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: yokawasa/action-setup-kube-tools@3e3886c11bfa25fe33f8eb90f59542dd151da442 # v0.13.1
        with:
          setup-tools: |
            helm
            kubeconform
          helm: '3.15.1'
          kubeconform: '0.7.0'

      - run: helm lint .
      - run: helm template . -f values.yaml | kubeconform -summary
      - run: helm plugin install https://github.com/helm-unittest/helm-unittest --version 1.0.2 || true
      - run: helm unittest .
